### ISSUE TITLE
Support NAME and SYMBOL not being exactly 32 character string

### ISSUE THREAD

**Issue by pixelcircuits** [FuelLabs/bridge-fungible-token#36]
We need to find a way to support NAME and SYMBOL not having to be exactly a 32 character string. Perhaps the config constant is still a fixed 32 character array, but we add logic in the getters to essentially trim leading and trailing whitespace? Right now sway doesn't seem to support variable length strings, so we'd have to wait on that first

**Comment by nfurfaro** [comment]
I'm not sure about how to proceed with this. The following doesn't seem much better than what we have:
```
NAME = { type = "str[32]", value = "\"MY_TOKEN000000000000000000000000\"" }
```
While we can use escapes in the Forc.toml, the actual Sway `str` type doesn't;t seem to allow them, so I can't do the following:
```
value = "\"MY_TOKEN\000000000000000000000000\"" 
```

**Comment by nfurfaro** [comment]
This is now done as of #57
